debug

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -9,53 +9,46 @@ on:
     - main
 
 jobs:
+  build:
     runs-on: ubuntu-latest
-
     steps:
-      build:
-      - uses: actions/checkout@v1
-      - uses: C2SM/sphinx-action@sphinx-latest
-        with:
-          pre-build-command: "apt-get update -y && apt-get install -y python-dev build-essential libgeos-dev"
-          docs-folder: "doc/"
-      # Great extra actions to compose with:
-      # Create an artifact of the html output.
-      - uses: actions/upload-artifact@v1
-        with:
-          name: DocumentationHTML
-          path: doc/_build/
-
-      publish:
-        if: github.ref == 'refs/heads/main'
-        - uses: actions/checkout@v1
-        - uses: actions/download-artifact@v3
-          with:
-            name: DocumentationHTML
-            path: doc/_build/
-        # Publish built docs to gh-pages branch.
-        # ===============================
-        - name: Commit documentation changes
-          run: |
-            pwd
-            ls doc
-            echo ' '
-            ls doc/_build
-            git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
-            cp -r doc/_build/html/* gh-pages/
-            cd gh-pages
-            touch .nojekyll
-            git config --local user.email "action@github.com"
-            git config --local user.name "GitHub Action"
-            git add .
-            git commit -m "Update documentation" -a || true
-            # The above command will fail if no changes were present, so we ignore
-            # that.
-        - name: Push changes
-          # this commit SHA corresponds to tag `v0.6.0`
-          uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
-          with:
-            force: true
-            branch: gh-pages
-            directory: gh-pages
-            github_token: ${{ secrets.GITHUB_TOKEN }}
-        # ===============================
+    - uses: actions/checkout@v1
+    - uses: C2SM/sphinx-action@sphinx-latest
+      with:
+        pre-build-command: "apt-get update -y && apt-get install -y python-dev build-essential libgeos-dev"
+        docs-folder: "doc/"
+    # Great extra actions to compose with:
+    # Create an artifact of the html output.
+    - uses: actions/upload-artifact@v1
+      with:
+        name: DocumentationHTML
+        path: doc/_build/
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+      if: github.ref == 'refs/heads/main'
+      run: |
+        pwd
+        ls doc
+        echo ' '
+        ls doc/_build
+        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+        cp -r doc/_build/html/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      if: github.ref == 'refs/heads/main'
+      # this commit SHA corresponds to tag `v0.6.0`
+      uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
+      with:
+        force: true
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
